# Generated by Django 4.2.19 on 2025-02-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный товар'),
        ),
    ]
